In [41]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import Binarizer
from sklearn.compose  import ColumnTransformer
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [42]:
df=pd.read_csv("Train.csv",usecols=['Age','Fare','SibSp','Parch','Survived'])
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [43]:
df['family'] = df['SibSp'] + df['Parch']

In [44]:
df.drop(columns=['SibSp','Parch'],inplace=True)
df.dropna(inplace=True)

In [45]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [46]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=30)

In [47]:
# without binarization
cl=DecisionTreeClassifier()
cl.fit(X_train,y_train)
y_pred=cl.predict(X_test)
acc=accuracy_score(y_test,y_pred)
acc

0.6790697674418604

In [48]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=8,scoring='accuracy'))

np.float64(0.6414794007490636)

In [49]:
#with bbinarization
trf=ColumnTransformer([('binary',Binarizer(copy=True),['family'])],remainder='passthrough')

trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [53]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.fit_transform(X_test)

pd.DataFrame(X_train_trf,columns=['family','Age','Fare'])

     family   Age     Fare
0       0.0  35.0   7.0500
1       1.0  32.0  15.8500
2       1.0  65.0  61.9792
3       0.0  28.0  13.0000
4       0.0  24.5   8.0500
..      ...   ...      ...
494     1.0  11.0  31.2750
495     1.0   9.0  31.3875
496     0.0  56.0  30.6958
497     0.0  32.0  30.5000
498     1.0   2.0  26.0000

[499 rows x 3 columns]

In [54]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.6325581395348837

In [55]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=8,scoring='accuracy'))

np.float64(0.6246098626716604)